In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"

# Including Metadata

``AUCMEDI`` allows us to include metadata. This is useful, because it might be, that we have some additional information alongside our images such as age or blood values that have some value for classification.  

We don't have such additional metadata for the dataset used here (images of colorectal cancer histology), but we will make some up for demonstation purposes.  

But fist, the data need to be loaded.  

## Downloading and preparing the data

First, the data need to be loaded and prepared for ``AUCMEDI``.  
If you have questions concering that part, just have a look in the corresponding notebook.

In [2]:
from pathlib import Path
import wget
import zipfile

import os
cwd = os.getcwd()
datadir = cwd + "/data"
Path(datadir).mkdir(parents=True, exist_ok=True)

#print('Beginning file download with wget module')

#url = 'https://zenodo.org/record/53169/files/Kather_texture_2016_image_tiles_5000.zip?download=1'
#wget.download(url, datadir)

#with zipfile.ZipFile("data/Kather_texture_2016_image_tiles_5000.zip","r") as zip_ref:
#    zip_ref.extractall("data")

from aucmedi.data_processing.io_data import input_interface
ds_loader = input_interface("directory", path_imagedir="data/Kather_texture_2016_image_tiles_5000", path_data=None, training=True, ohe=False)
(samples, class_ohe, nclasses, class_names, image_format) = ds_loader


E:\Daten\Uni\MISIT\MyFork\aucmedi\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Generating Metadata

Now we will generate some random metadata. Of course they won't have value for classification, but we will see how to include the metadata into the ``AUCMEDI`` pipeline.

In [3]:
import numpy as np
from numpy import random

age=random.randint(low=30, high=100, size=(5000))
blood=random.randn(5000)
metadata = np.vstack((age,blood)).T

Let's see what our metadata looks like:

In [4]:
metadata

array([[83.        ,  0.54563044],
       [35.        , -1.2822862 ],
       [68.        , -1.02521374],
       ...,
       [49.        , -0.13103798],
       [51.        ,  0.36743011],
       [82.        , -0.93909057]])

So our metadata are a 2-dimensional numpy array with the dimensions (n_samples, n_variables).  
In the first column are is the age and in the second column a blood-value of the samples (randomly generated).  

## Splitting our data in train-, test- and validation set

When splitting the dataset with ``sampling_split`` we also include the metadata to the splitting (using the argument metadata) so that the metadata get split as well.

In [5]:
from aucmedi.sampling.split import sampling_split
train, validation, test = sampling_split(samples, class_ohe, metadata=metadata, sampling=[0.5, 0.25, 0.25], 
                                         stratified=True, iterative=False, seed=123)

In [6]:
train

(array(['07_ADIPOSE\\15FFE_CRC-Prim-HE-03_012.tif_Row_1_Col_601.tif',
        '01_TUMOR\\10264_CRC-Prim-HE-07_025.tif_Row_1801_Col_1.tif',
        '07_ADIPOSE\\13CEE_CRC-Prim-HE-05_032.tif_Row_1501_Col_901.tif',
        ...,
        '08_EMPTY\\1470E_CRC-Prim-HE-06_005.tif_Row_4351_Col_2851.tif',
        '07_ADIPOSE\\14420_CRC-Prim-HE-10_020.tif_Row_601_Col_1801.tif',
        '07_ADIPOSE\\163E5_CRC-Prim-HE-06_004.tif_Row_1801_Col_451.tif'],
       dtype='<U64'),
 array([[0, 0, 0, ..., 0, 1, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0]], dtype=uint8),
 array([[81.        ,  0.88900853],
        [80.        , -1.07032327],
        [68.        ,  1.20105755],
        ...,
        [46.        , -0.39287342],
        [90.        ,  0.36090724],
        [78.        , -0.36892493]]))

## Define the model

Now we define our ``NeuralNetwork``. If you have questions concering that, have a look in the notebook "Custom Architecture" or "3 Pillars".  

Importantly we have  to define the argument `meta_variables` as 2 here, so that AUCMEDI knows to include these variables.

In [7]:
from aucmedi.neural_network.model import NeuralNetwork
import torchmetrics
import torch

f1Score = torchmetrics.F1Score(task="multiclass", num_classes=nclasses, average="macro")

model = NeuralNetwork(n_labels=nclasses, channels=3, 
                      loss=torch.nn.CrossEntropyLoss(), 
                      activation_output="softmax", pretrained_weights=False, n_meta_variables = 2)

## Train the model

Now, the model can be trained. If you have questions concering that, have a look at the notebook "Custom Architecture" or "3 Pillars".  

Here, it is importatnt that we include the ``metadata`` for __each__ ``create_data_loader``. As you can see in the output above, the ``metadata`` for train, are in ``train[2]`` and accordingly the ``metadata`` for validation are in ``validation[2]``.

In [8]:
from aucmedi.data_processing.data_generator import create_data_loader

train_generator = create_data_loader(samples=train[0], path_imagedir="data/Kather_texture_2016_image_tiles_5000",
                                               labels=train[1], metadata=train[2], resize=model.arch_resolution, 
                                               standardize_mode=model.arch_standardize, 
                                               image_format=image_format, batch_size=32, data_aug=None, 
                                               grayscale=False, subfunctions=[], prepare_images=False, 
                                               sample_weights=None, seed=123, workers=1)
val_generator = create_data_loader(samples=validation[0], path_imagedir="data/Kather_texture_2016_image_tiles_5000",
                                               labels=validation[1], metadata=validation[2], resize=model.arch_resolution, 
                                               standardize_mode=model.arch_standardize, 
                                               image_format=image_format, batch_size=32, data_aug=None, 
                                               grayscale=False, subfunctions=[], prepare_images=False, 
                                               sample_weights=None, seed=123, workers=1)

history = model.train(training_generator=train_generator, validation_generator=val_generator, epochs=20, iterations=None, 
                                         callbacks=[], transfer_learning=False)

Epoch 1/20, Loss: 2.0187,  Val Loss: 1.6307, Time: 17.04s


Epoch 2/20, Loss: 1.4621,  Val Loss: 1.3069, Time: 16.87s


Epoch 3/20, Loss: 1.3184,  Val Loss: 1.1040, Time: 16.89s


Epoch 4/20, Loss: 1.1419,  Val Loss: 0.9131, Time: 16.97s


Epoch 5/20, Loss: 1.0320,  Val Loss: 0.8384, Time: 16.91s


Epoch 6/20, Loss: 0.9408,  Val Loss: 0.7654, Time: 17.32s


Epoch 7/20, Loss: 0.8902,  Val Loss: 0.6996, Time: 17.22s


Epoch 8/20, Loss: 0.8280,  Val Loss: 0.6917, Time: 17.29s


Epoch 9/20, Loss: 0.7623,  Val Loss: 0.6565, Time: 17.31s


Epoch 10/20, Loss: 0.7656,  Val Loss: 0.6375, Time: 17.31s


Epoch 11/20, Loss: 0.7192,  Val Loss: 0.6199, Time: 17.36s


Epoch 12/20, Loss: 0.7066,  Val Loss: 0.6002, Time: 17.48s


Epoch 13/20, Loss: 0.6833,  Val Loss: 0.5699, Time: 17.26s


Epoch 14/20, Loss: 0.6637,  Val Loss: 0.5511, Time: 17.23s


Epoch 15/20, Loss: 0.6605,  Val Loss: 0.5217, Time: 17.38s


Epoch 16/20, Loss: 0.6415,  Val Loss: 0.5481, Time: 17.42s


Epoch 17/20, Loss: 0.6098,  Val Loss: 0.4941, Time: 17.17s


Epoch 18/20, Loss: 0.5895,  Val Loss: 0.4944, Time: 17.12s


Epoch 19/20, Loss: 0.5920,  Val Loss: 0.4929, Time: 17.23s


Epoch 20/20, Loss: 0.5850,  Val Loss: 0.4982, Time: 17.23s


If you want to know how to evaluate the performance of your model, have a look in the corresponding notebook.